name: Bump version
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: Bump version and push tag
      uses: ministryofjustice/opg-github-actions/actions/semver@a2907c7c7be94301c965ace76a2cfa407ad6fc88 # v4.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        prerelease: false
        create_release: false
        default_bump: minor
        without_prefix: false
